substitutions:
  name: "buderus-km271"

esphome:
  name: "${name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  # name_add_mac_suffix: true

  platformio_options:
    upload_speed: 921600
    #board_build.f_flash: 80000000L
    #board_build.partitions: "default_8MB.csv
    #upload_flash_size: "8MB"

  # This will allow for (future) project identification,
  # configuration and updates.
  #project:
  #  name: the78mole.km271-wifi
  #  version: "1.0"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
#  password: "xxx"

wifi:
#  ssid: "test"
#  password: "testtest"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "KM271 Fallback Hotspot"
    password: ""

dashboard_import:
  package_import_url: github://man55/esphome_buderus/components/km271_wifi/km271-for-friends.yaml@main

captive_portal:
#  keep_user_credentials: true

uart:
  id: uart_bus
  tx_pin: GPIO2
  rx_pin: GPIO4
  baud_rate: 2400

external_components:
  - source: github://man55/esphome_buderus@main
    components: [ km271_wifi ]
    refresh:    1sec
#  - source:
#    type: local
#      path: my_components/components
#    components: [ km271_wifi ]


#esp32_improv:
#  authorizer: improvble
#  authorized_duration: 120s
#  status_indicator: led3
#  identify_duration: 60s

#improv_serial:


status_led:
  id: ledgn1
  pin:
    number: GPIO21
    inverted: true

km271_wifi:
  - id: budoil
    uart_id: uart_bus

binary_sensor:
  - platform: gpio
    id: improvble
    name: "USER 2"
    pin:
      number: GPIO27
      inverted: true
      mode:
        input: true
        pullup: true

# Above is all the "give-away hardware suggestion stuff"
# It is the place for cleanup of to reduce flash footprint, like:
# improv, captive portal, dashboard_import,...)
##################################################################

##################################################################
# Below is the real example stuff

  - platform: km271_wifi
    # Betriebswerte 1 HK1
    heating_circuit_1_switch_off_optimization:
      name: "HK1 Оптимизация отключения"
    heating_circuit_1_switch_on_optimization:
      name: "HK1 Оптимизация включения"
    heating_circuit_1_automatic:
      name: "HK1 Авторежим"
    heating_circuit_1_ww_priority_processing:
      name: "HK1 Warmwasservorrang"
    heating_circuit_1_screed_drying:
      name: "HK1 Приоритет ГВС"
    heating_circuit_1_holiday:
      name: "HK1 Отпуск"
    heating_circuit_1_antifreeze:
      name: "HK1 Защита от замерзания"
    heating_circuit_1_manually:
      name: "HK1 Ручной режим"
    # Betriebswerte 2 HK1
    heating_circuit_1_summer:
      name: "HK1 Летний режим"
    heating_circuit_1_day:
      name: "HK1 Дневной режим"
    heating_circuit_1_no_comm_with_rc:
      name: "HK1 Нет связи с ПУ"
    heating_circuit_1_rc_faulty:
      name: "HK1 ПУ неисправность"
    heating_circuit_1_flow_sensor_error:
      name: "HK1 Ошибка расходомера"
    heating_circuit_1_max_flow:
      name: "HK1 Максимальный поток"
    heating_circuit_1_external_fault_input:
      name: "HK1 Внешняя ошибка"
    # Betriebswerte 1 HK2
    heating_circuit_2_switch_off_optimization:
      name: "HK2 Оптимизация отключения"
    heating_circuit_2_switch_on_optimization:
      name: "HK2 Оптимизация включения"
    heating_circuit_2_automatic:
      name: "HK2 Авторежим"
    heating_circuit_2_ww_priority_processing:
      name: "HK2 Приоритет ГВС"
    heating_circuit_2_screed_drying:
      name: "HK2 Сушка стяжки"
    heating_circuit_2_holiday:
      name: "HK2 Отпуск"
    heating_circuit_2_antifreeze:
      name: "HK2 Защита от замерзания"
    heating_circuit_2_manually:
      name: "HK2 Ручной режим"
    # Betriebswerte 2 HK2
    heating_circuit_2_summer:
      name: "HK2 Летний режим"
    heating_circuit_2_day:
      name: "HK2 Дневной режим"
    heating_circuit_2_no_comm_with_rc:
      name: "HK2 Нет связи с ПУ"
    heating_circuit_2_rc_faulty:
      name: "HK2 ПУ неисправность"
    heating_circuit_2_flow_sensor_error:
      name: "HK2 Ошибка расходомера"
    heating_circuit_2_max_flow:
      name: "HK2 Максимальный поток"
    heating_circuit_2_external_fault_input:
      name: "HK2 Внешняя ошибка"
    # Betriebswerte 1 WW
    ww_automatic:
      name: "ГВС Авторежим"
    ww_disinfection:
      name: "ГВС Дезинфекция"
    ww_reload:
      name: "ГВС Перегрузка"
    ww_holiday:
      name: "ГВС Отпуск"
    ww_error_disinfection:
      name: "ГВС Ошибка дезинфекции"
    ww_error_sensor:
      name: "ГВС Ошибка датчика"
    ww_error_stays_cold:
      name: "Ошибка ГВС Остаётся холодной"
    ww_error_anode:
      name: "ГВС Ошибка анода"
    # Betriebswerte 2 WW
    ww_loading:
      name: "ГВС Загрузка"
    ww_manually:
      name: "ГВС Ручной режим"
    ww_reloading:
      name: "ГВС Перезарядка"
    ww_switch_off_optimization:
      name: "ГВС Оптимизация отключения"
    ww_switch_on_optimization:
      name: "ГВС Оптимизация включения"
    ww_day_mode:
      name: "ГВС Дневной режим"
    ww_post_processing:
      name: "ГВС Постобработка"
    ww_priority_processing:
      name: "ГВС Приоритет"
    # Kesselfehler
    error_burner_malfunction:
      name: "Ошибка Неисправность горелки"
    error_boiler_sensor:
      name: "Ошибка Датчик котла"
    error_additional_sensor:
      name: "Ошибка Дополнительный датчик"
    error_boiler_stays_cold:
      name: "Ошибка Котел остается холодным"
    error_exhaust_gas_sensor:
      name: "Ошибка Датчик выхлопных газов"
    error_exhaust_gas_over_limit:
      name: "Ошибка Выхлопные газы выше предела"
    error_safety_chain_released:
      name: "Ошибка Сработала предохранительная цепь"
    error_external_disturbance:
      name: "Ошибка Внешнее вмешательство"
    # Kesselbetrieb
    boiler_emission_test:
      name: "Котёл Тест эмиссии"
    boiler_1st_stage_operation:
      name: "Работа 1-й ступени"
    boiler_protection:
      name: "Защита котла"
    boiler_under_operation:
      name: "Котел работает"
    boiler_performance_free:
      name: "Котёл Производительность свободная"
    boiler_performance_high:
      name: "Котёл Производительность высокая"
    boiler_2st_stage_operation:
      name: "Работа 2-й ступени"
    boiler_actuation:
      name: "Котёл Контроль горелки"
  #Alarmstatus
    alarm_exhaust_gas_sensor:
      name: "Тревога Датчик выхлопных газов"
    alarm_boiler_flow_sensor:
      name: "Тревога Расходомер котла"
    alarm_burner:
      name: "Тревога Горелка"
    alarm_heating_circuit_2_flow_sensor:
      name: "Тревога HK2 Расходомер"
  #Other stuff
    load_pump_running:
      name: "Нагрузочный насос работает"
    circulation_pump_running:
      name: "Циркуляционный насос работает"
    solar_pump_lowering:
      name: "Понижение солнечного насоса"



output:
  - platform: gpio
    id: led3
    #name: LED3_Yellow
    pin:
      number: 23
      mode: OUTPUT
      inverted: true
  - platform: gpio
    id: led4
    #name: LED4_Red
    pin:
      number: 25
      mode: OUTPUT
      inverted: true

button:
  - platform: restart
    name: "KM271-WiFi Restart"
# Some older Example for sending raw telegrams, replaced by a select
#  - platform: template
#    name: "KM271 WW-Bereitung Aus"
#    on_press:
#      - lambda:
#          uint8_t command[] = {0x0C, 0x0E, 0x00, 0x65, 0x65, 0x65, 0x65, 0x65};
#          budoil->writer.enqueueTelegram(command, 8);
#  - platform: template
#    name: "KM271 WW-Bereitung Ein"
#    on_press:
#      - lambda:
#          uint8_t command[] = {0x0C, 0x0E, 0x01, 0x65, 0x65, 0x65, 0x65, 0x65};
#          budoil->writer.enqueueTelegram(command, 8);
#  - platform: template
#    name: "KM271 WW-Bereitung Auto"
#    on_press:
#      - lambda:
#          uint8_t command[] = {0x0C, 0x0E, 0x02, 0x65, 0x65, 0x65, 0x65, 0x65};
#          budoil->writer.enqueueTelegram(command, 8);


number:
  - platform: km271_wifi
    config_ww_temperature:
      name: "Целевая t°горячей воды днём"
      mode: slider
    config_frost_switch_temperature:
      name: "t° переключателя антизамерзания"
      mode: slider

    config_heating_circuit_1_room_target_temperature_night:
      name: "Целевая t° ночью"
      mode: slider
    config_heating_circuit_1_room_target_temperature_day:
      name: "Целевая t° днём"
      mode: slider
    config_heating_circuit_1_holiday_target_temperature:
      name: "Целевая t° отпуска"
      mode: slider
    config_heating_circuit_1_flow_temperature_max:
      name: "t° подачи"
      mode: slider
    config_heating_circuit_1_design_temperature:
      name: "t° расчетная"
      mode: slider
    config_heating_circuit_1_room_temperature_offset:
      name: "Смещение комнатной t°"
      mode: slider
    config_heating_circuit_1_holiday_days:
      name: "Дней отпуска"
      mode: slider

    config_heating_circuit_2_room_target_temperature_night:
      name: "HK2 Целевая t° ночью"
      mode: slider
    config_heating_circuit_2_room_target_temperature_day:
      name: "HK2 Целевая t° днём"
      mode: slider
    config_heating_circuit_2_holiday_target_temperature:
      name: "HK2 Целевая t° отпуска"
      mode: slider
    config_heating_circuit_2_flow_temperature_max:
      name: "HK2 t° подачи"
      mode: slider
    config_heating_circuit_2_design_temperature:
      name: "HK2 t° расчетная"
      mode: slider
    config_heating_circuit_2_room_temperature_offset:
      name: "HK2 Смещение комнатной t°"
      mode: slider
    config_heating_circuit_2_holiday_days:
      name: "HK2 Дней отпуска"
      mode: slider

select:
  - platform: km271_wifi
    config_ww_operation_mode:
      name: "ГВС Режим работы"
    config_ww_circular_pump_interval:
      name: "ГВС Интервал циркуляционного насоса"

    config_heating_circuit_1_summer_winter_switch_temperature:
      name: "t° перехода зима-лето"
    config_heating_circuit_1_operation_mode:
      name: "Режим работы контура"
    config_heating_circuit_1_lowering_type:
      name: "Тип понижения контура"
    config_heating_circuit_1_heating_system_type:
      name: "Модель отопления"
    config_heating_circuit_1_heating_program:
      name: "Программа отопления"

    config_heating_circuit_2_summer_winter_switch_temperature:
      name: "HK2 t° перехода зима-лето"
    config_heating_circuit_2_operation_mode:
      name: "HK2 Режим работы контура"
    config_heating_circuit_2_lowering_type:
      name: "HK2 Тип понижения контура"
    config_heating_circuit_2_heating_system_type:
      name: "HK2 Модель отопления"
    config_heating_circuit_2_heating_program:
      name: "HK2 Программа отопления"

sensor:
  - platform: km271_wifi
    heating_circuit_1_flow_target_temperature:
      name: "Целевая t° подачи"
    heating_circuit_1_flow_temperature:
      name: "t° подачи"
    heating_circuit_1_room_target_temperature:
      name: "Целевая t° в доме"
    heating_circuit_1_room_temperature:
      name: "t° в доме"
    heating_circuit_1_pump_power:
      name: "Мощность насоса"
    heating_circuit_1_mixer_position:
      name: "Положение смесителя"
    heating_circuit_1_curve_p10:
      name: "Кривая нагрева +10 °C"
    heating_circuit_1_curve_0:
      name: "Кривая нагрева 0 °C"
    heating_circuit_1_curve_n10:
      name: "Кривая нагрева -10 °C"
    heating_circuit_2_flow_target_temperature:
      name: "HK2 Целевая t° подачи"
    heating_circuit_2_flow_temperature:
      name: "HK2 t° подачи"
    heating_circuit_2_room_target_temperature:
      name: "HK2 Целевая t° в доме"
    heating_circuit_2_room_temperature:
      name: "HK2 t° в доме"
    heating_circuit_2_pump_power:
      name: "HK2 Мощность насоса"
    heating_circuit_2_mixer_position:
      name: "HK2 Положение смесителя"
    heating_circuit_2_curve_p10:
      name: "HK2 Кривая нагрева +10 °C"
    heating_circuit_2_curve_0:
      name: "HK2 Кривая нагрева 0 °C"
    heating_circuit_2_curve_n10:
      name: "HK2 Кривая нагрева -10 °C"
    ww_target_temperature:
      name: "ГВС Целевая t°"
    ww_temperature:
      name: "ГВС t°"
    boiler_target_temperature:
      name: "Целевая t° котла"
    boiler_temperature:
      name: "t° котла"
    boiler_turn_on_temperature:
      name: "t° включения котла"
    boiler_turn_off_temperature:
      name: "t° выключения котла"
    exhaust_gas_temperature:
      name: "t° выхлопных газов"
    outdoor_temperature:
      name: "t° на улице"
    attenuated_outdoor_temperature:
      name: "Сглаженная t° на улице"
    boiler_runtime_1:
      name: "Время работы горелки К1"
    boiler_runtime_2:
      name: "Время работы горелки К2"


  - platform: wifi_signal
    name: "KM217 WiFi Signal Sensor"
    update_interval: 60s

  - platform: adc
    pin: 36
    unit_of_measurement: "V"
    name: "KM217 5V Supply"
    accuracy_decimals: 2
    update_interval: 5s
    attenuation: 6dB
    filters:
      - multiply: 28.1826
      - throttle_average: 60s

switch:
  - platform: gpio
    name: LED2_Green
    pin:
      number: 22
      mode: OUTPUT
      inverted: true

text_sensor:
  - platform: km271_wifi
    firmware_version:
      name: "Firmware_version"
